### ISSUE TITLE
sous windows

### ISSUE THREAD

**Issue by JEROME-TICTEC** [JGarderon/Regles#3]
la gestion des arguments semble différente sous windows:
https://doc.rust-lang.org/stable/std/env/fn.args_os.html

voici une méthode qui fonctionne sous Windows: pour des arguments obligatoires et dans le même ordre...

> use std::env;
> 
> fn main() {
>     let args: Vec<String> = env::args().collect();
> 
>     let rt = &args[1];
>     let rs = &args[2];
> 
>     println!("RESOLUTION_TYPE", rt);
>     println!("REGLES_SOURCE", rs);
> }

avec comme commandes:
C:\Users\toto\Documents\projects\Regles-master>
cargo build
cd target\debug
Regle.exe asservi regles.txt

comment différencier l'os en Rust pour pouvoir switcher la collecte des arguments ?

si non, il reste l'option d'un fichier .ini systématiquement situé dans le même dossier que le main.rs
mais le chemin de regles.txt sera, de toute façon,  de syntaxe différente selon l'os.

Cordialement,
jérôme

**Comment by JGarderon** [comment]
Bonjour Jérôme, 

Je monte une machine Windows, car je n'ai pas commencé encore les tests sous Windows. 
Pour le lien que tu indiques, évoques-tu la phrase "On Windows this is not done, and such arguments are passed as-is" ? Si oui, c'est pour [l'expansion des variables](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) du Shell. En soi je dois pouvoir espérer avoir une gestion commune aux deux familles d'OS. 

Pour la partie argument, as-tu vu que j'ai poussé une nouvelle _release_  sur ce point justement ? 
https://github.com/JGarderon/Regles/releases/tag/1.0.2

A te lire, 

Julien.

**Comment by JGarderon** [comment]
Je te confirme que c'est fonctionnel pour la _release_ 1.0.2. J'ai pris un Windows Server 2016 que j'avais sous la main :
```powershell
PS C:\Users\Administrateur> cd \\VBOXSVR\Regles
PS Microsoft.PowerShell.Core\FileSystem::\\VBOXSVR\Regles> cargo run -- --resolution asservi --regles .\regles.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
     Running `target\debug\Regle.exe --resolution asservi --regles .\regles.txt`
initier
n
# ERREUR 'erreur fatale durant la résolution' - dépilement :
# ... Le processus distant n'est pas prêt à exécuter les consignes du moteur de règles
error: process didn't exit successfully: `target\debug\Regle.exe --resolution asservi --regles .\regles.txt` (exit code: 2)
PS Microsoft.PowerShell.Core\FileSystem::\\VBOXSVR\Regles> cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
PS Microsoft.PowerShell.Core\FileSystem::\\VBOXSVR\Regles> .\target\debug\Regle.exe
# ERREUR 'erreur fatale durant la résolution' - dépilement :
# ... La variable déclarant le chemin source des règles n'est pas disponible
PS Microsoft.PowerShell.Core\FileSystem::\\VBOXSVR\Regles> .\target\debug\Regle.exe --resolution asservi --regles .\regl
es.txt
initier
n
# ERREUR 'erreur fatale durant la résolution' - dépilement :
# ... Le processus distant n'est pas prêt à exécuter les consignes du moteur de règles
```
Note que pour le lancement avec `cargo run`, tu dois précéder les arguments pour l'exécutable cible avec "--". 

Peux-tu me confirmer que c'est bon pour toi ? (_je ferme le ticket dans les jours à venir_)

A te lire, 

Julien.
